const $=s=>document.querySelector(s);
const algorithms={
  classic:[['caesar','Шифр Цезаря'],['vigenere','Шифр Виженера'],['atbash','Атбаш'],['rot13','ROT13'],['polybius','Квадрат Полибия 6×6'],['rail','Железнодорожная изгородь']],
  encoding:[['base64','Base64'],['hex','HEX'],['binary','Двоичный код'],['url','URL-кодирование'],['morse','Азбука Морзе']],
  modern:[['aes','AES-GCM по паролю']]
};
const ru='АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ',en='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const morse={А:'.-',Б:'-...',В:'.--',Г:'--.',Д:'-..',Е:'.',Ж:'...-',З:'--..',И:'..',Й:'.---',К:'-.-',Л:'.-..',М:'--',Н:'-.',О:'---',П:'.--.',Р:'.-.',С:'...',Т:'-',У:'..-',Ф:'..-.',Х:'....',Ц:'-.-.',Ч:'---.',Ш:'----',Щ:'--.-',Ъ:'--.--',Ы:'-.--',Ь:'-..-',Э:'..-..',Ю:'..--',Я:'.-.-',A:'.-',B:'-...',C:'-.-.',D:'-..',E:'.',F:'..-.',G:'--.',H:'....',I:'..',J:'.---',K:'-.-',L:'.-..',M:'--',N:'-.',O:'---',P:'.--.',Q:'--.-',R:'.-.',S:'...',T:'-',U:'..-',V:'...-',W:'.--',X:'-..-',Y:'-.--',Z:'--..','0':'-----','1':'.----','2':'..---','3':'...--','4':'....-','5':'.....','6':'-....','7':'--...','8':'---..','9':'----.'};
let active='classic';
function alphabetFor(text){const choice=$('#alphabet').value;if(choice==='ru')return ru;if(choice==='en')return en;return /[А-ЯЁ]/i.test(text)?ru:en}
function shift(text,n){const abc=alphabetFor(text),len=abc.length;return [...text].map(ch=>{const up=ch.toUpperCase(),i=abc.indexOf(up);if(i<0)return ch;const out=abc[(i+n+len)%len];return ch===up?out:out.toLowerCase()}).join('')}
function vig(text,key,dir){const abc=alphabetFor(text),clean=[...key.toUpperCase()].filter(c=>abc.includes(c));if(!clean.length)throw Error('Ключ должен содержать буквы выбранного алфавита');let j=0;return [...text].map(ch=>{const up=ch.toUpperCase(),i=abc.indexOf(up);if(i<0)return ch;const k=abc.indexOf(clean[j++%clean.length]),out=abc[(i+dir*k+abc.length)%abc.length];return ch===up?out:out.toLowerCase()}).join('')}
function atbash(text){const abc=alphabetFor(text);return [...text].map(ch=>{const up=ch.toUpperCase(),i=abc.indexOf(up);if(i<0)return ch;const out=abc[abc.length-1-i];return ch===up?out:out.toLowerCase()}).join('')}
function poly(text,decode){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';if(decode)return text.trim().split(/[\s,;–—-]+/).filter(Boolean).map(x=>{if(!/^[1-6]{2}$/.test(x))return '�';return chars[(+x[1]-1)*6+(+x[0]-1)]}).join('');return [...text.toUpperCase()].map(c=>{const i=chars.indexOf(c);return i<0?c:`${i%6+1}${Math.floor(i/6)+1}`}).join(' ')}
function rail(text,rails,decode){if(rails<2)throw Error('Ключ — число рядов от 2');const pattern=[],cycle=2*rails-2;for(let i=0;i<text.length;i++)pattern.push(Math.min(i%cycle,cycle-i%cycle));if(!decode){return Array.from({length:rails},(_,r)=>[...text].filter((_,i)=>pattern[i]===r).join('')).join('')}const counts=Array(rails).fill(0);pattern.forEach(r=>counts[r]++);const rows=[];let p=0;counts.forEach(n=>{rows.push([...text.slice(p,p+n)]);p+=n});return pattern.map(r=>rows[r].shift()).join('')}
function bytesToB64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function b64ToBytes(s){const b=atob(s.replace(/\s/g,'')),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function aes(encrypt){if(!crypto.subtle)throw Error('AES требует современный браузер или локальный сервер');const password=$('#key').value;if(!password)throw Error('Введите пароль');let salt,iv;if(encrypt){salt=crypto.getRandomValues(new Uint8Array(16));iv=crypto.getRandomValues(new Uint8Array(12));$('#salt').value=bytesToB64(salt);$('#iv').value=bytesToB64(iv)}else{salt=b64ToBytes($('#salt').value);iv=b64ToBytes($('#iv').value);if(salt.length!==16||iv.length!==12)throw Error('Неверная соль или IV')}const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,[encrypt?'encrypt':'decrypt']);const data=encrypt?new TextEncoder().encode($('#input').value):b64ToBytes($('#input').value);const out=await crypto.subtle[encrypt?'encrypt':'decrypt']({name:'AES-GCM',iv},key,data);return encrypt?bytesToB64(new Uint8Array(out)):new TextDecoder().decode(out)}
function transform(decode=true){const a=$('#algorithm').value,t=$('#input').value,k=$('#key').value;switch(a){case'caesar':return shift(t,(decode?-1:1)*(parseInt(k)||0));case'vigenere':return vig(t,k,decode?-1:1);case'atbash':return atbash(t);case'rot13':return shift(t,13);case'polybius':return poly(t,decode);case'rail':return rail(t,parseInt(k)||2,decode);case'base64':return decode?new TextDecoder().decode(b64ToBytes(t)):bytesToB64(new TextEncoder().encode(t));case'hex':return decode?new TextDecoder().decode(Uint8Array.from((t.match(/[0-9a-f]{2}/gi)||[]).map(x=>parseInt(x,16)))):[...new TextEncoder().encode(t)].map(x=>x.toString(16).padStart(2,'0')).join(' ');case'binary':return decode?new TextDecoder().decode(Uint8Array.from(t.trim().split(/\s+/).map(x=>{if(!/^[01]{8}$/.test(x))throw Error('Используйте группы по 8 бит');return parseInt(x,2)}))):[...new TextEncoder().encode(t)].map(x=>x.toString(2).padStart(8,'0')).join(' ');case'url':return decode?decodeURIComponent(t):encodeURIComponent(t);case'morse':{const reverse=Object.fromEntries(Object.entries(morse).map(([x,y])=>[y,x]));return decode?t.trim().split(/\s*\/\s*|\s{2,}/).map(w=>w.split(/\s+/).map(c=>reverse[c]||'�').join('')).join(' '):t.toUpperCase().split(/\s+/).map(w=>[...w].map(c=>morse[c]||'�').join(' ')).join(' / ')}case'aes':return aes(!decode)}}
function updateAlgorithms(){const select=$('#algorithm');select.innerHTML=algorithms[active].map(([v,n])=>`<option value="${v}">${n}</option>`).join('');updateUI()}
function updateUI(){const a=$('#algorithm').value,needsKey=['caesar','vigenere','rail','aes'].includes(a);$('#keyWrap').classList.toggle('hidden',!needsKey);$('#alphabetWrap').classList.toggle('hidden',!['caesar','vigenere','atbash','rot13'].includes(a));$('#modernFields').classList.toggle('hidden',a!=='aes');$('#tryAll').classList.toggle('hidden',a!=='caesar');$('#key').type=a==='aes'?'password':'text';$('#key').placeholder=a==='caesar'?'Например, 3':a==='rail'?'Например, 3':a==='aes'?'Пароль':'Ключевое слово';$('#keyHint').textContent=a==='aes'?'Не сохраняется':a==='caesar'?'Число сдвига':'';$('#variants').classList.add('hidden')}
async function run(decode){try{const input=$('#input').value;if(!input.trim())throw Error('сначала введите текст');const algorithm=$('#algorithm').value;if(['caesar','vigenere','aes'].includes(algorithm)&&!$('#key').value.trim())throw Error('укажите ключ');$('#status').textContent='Обработка…';const value=await transform(decode);$('#output').value=value;$('#status').textContent=`Готово · ${value.length} символов`}catch(e){$('#output').value='';$('#status').textContent='Ошибка: '+(e.name==='OperationError'?'неверный пароль или параметры':e.message)}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.tab;updateAlgorithms()});
$('#algorithm').onchange=updateUI;$('#decrypt').onclick=()=>run(true);$('#encrypt').onclick=()=>run(false);$('#input').oninput=e=>$('#inputCount').textContent=e.target.value.length;$('#clear').onclick=()=>{$('#input').value='';$('#output').value='';$('#inputCount').textContent=0};$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#output').value);$('#status').textContent='Скопировано'};$('#swap').onclick=()=>{[$('#input').value,$('#output').value]=[$('#output').value,$('#input').value];$('#inputCount').textContent=$('#input').value.length};$('#tryAll').onclick=()=>{const t=$('#input').value,abc=alphabetFor(t),box=$('#variants');box.innerHTML=Array.from({length:abc.length-1},(_,i)=>`<div class="variant"><b>${i+1}</b><span>${shift(t,-i-1).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</span></div>`).join('');box.classList.remove('hidden')};
updateAlgorithms();
